# Generated by Django 4.1.1 on 2022-12-16 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ItemStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "status",
                    models.ForeignKey(
                        default="Unprocessed",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.itemstatus",
                        to_field="title",
                    ),
                ),
            ],
        ),
    ]
