# Generated by Django 4.1.1 on 2022-12-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_alter_settings_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="items_per_grid",
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
    ]
