# Generated by Django 4.1.1 on 2022-12-20 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_settings_items_per_grid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Settings",
        ),
    ]
