# Generated by Django 4.1.1 on 2022-12-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="gis_validation",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="items_per_grid",
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
    ]
